[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.28"
bytecode_hash = "none"
cbor_metadata = false
viaIR = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
fs_permissions = [{ access = "read-write", path = "./deployments" }]


[fmt]
line_length = 100
number_underscore = "thousands"
sort_imports = true
tab_width = 4
